sudo: false
bundler_args: --jobs=3 --retry=3
cache:
  - bundler
before_install:
  - gem update --remote bundler
language: ruby
rvm:
  - 2.1
  - 2.2
  - jruby
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_script:
  - cp spec/searchmetrics_config.yml.example spec/searchmetrics_config.yml
script:
  - bundle exec rake
  - bundle exec rubocop
